// Sample data shaped exactly like the raw n8n workflow output, used only
// when a user clicks "View Sample Results" on the search page — handy for
// demoing or developing the UI without a live backend call.
export const mockBusinesses = [
  {
    place_id: "mock-1",
    name: "Layers Bakery",
    address: "12 MM Alam Road, Gulberg III, Lahore, Pakistan",
    phone: "+92 42 3571 2200",
    website: "https://layersbakery.pk/",
    has_website: true,
    rating: 4.6,
    review_count: 18,
    google_maps_url: "https://maps.google.com/?cid=1",
    business_status: "OPERATIONAL",
    category: "bakery",
    priority_tier: 1,
    owner_name: "Not found",
    email: "hello@layersbakery.pk",
    instagram: "https://www.instagram.com/layersbakery/",
    facebook: "https://www.facebook.com/layersbakery/",
    linkedin: "Not found",
    additional_notes: "Popular for custom cakes and pastries; active on Instagram.",
  },
  {
    place_id: "mock-2",
    name: "The Daily Loaf",
    address: "45 MM Alam Road, Lahore, Pakistan",
    phone: "+92 300 1234567",
    website: null,
    has_website: false,
    rating: 4.2,
    review_count: 9,
    google_maps_url: "https://maps.google.com/?cid=2",
    business_status: "OPERATIONAL",
    category: "bakery",
    priority_tier: 1,
    owner_name: "Ahmed Raza",
    email: "Not found",
    instagram: "Not found",
    facebook: "https://www.facebook.com/thedailyloaf.pk/",
    linkedin: "Not found",
    additional_notes: "No website found; small neighbourhood bakery, high potential lead.",
  },
  {
    place_id: "mock-3",
    name: "Sweet Crust Bakers",
    address: "8 Zafar Ali Road, Lahore, Pakistan",
    phone: "+92 42 3588 1122",
    website: "https://sweetcrust.com/",
    has_website: true,
    rating: 4.8,
    review_count: 132,
    google_maps_url: "https://maps.google.com/?cid=3",
    business_status: "OPERATIONAL",
    category: "bakery",
    priority_tier: 2,
    owner_name: "Not found",
    email: "info@sweetcrust.com",
    instagram: "https://www.instagram.com/sweetcrustbakers/",
    facebook: "Not found",
    linkedin: "https://pk.linkedin.com/company/sweet-crust-bakers",
    additional_notes: "Established chain with loyal following; considering delivery expansion.",
  },
  {
    place_id: "mock-4",
    name: "Bread & Bean Co.",
    address: "22 Cavalry Ground, Lahore, Pakistan",
    phone: "+92 321 9988776",
    website: null,
    has_website: false,
    rating: 4.0,
    review_count: 5,
    google_maps_url: "https://maps.google.com/?cid=4",
    business_status: "OPERATIONAL",
    category: "bakery",
    priority_tier: 1,
    owner_name: "Not found",
    email: "Not found",
    instagram: "Not found",
    facebook: "Not found",
    linkedin: "Not found",
    additional_notes: "Very new listing, minimal online presence — strong outreach candidate.",
  },
  {
    place_id: "mock-5",
    name: "Heritage Bake House",
    address: "3 Liberty Market, Lahore, Pakistan",
    phone: "+92 42 3575 9090",
    website: "https://heritagebakehouse.pk/",
    has_website: true,
    rating: 4.4,
    review_count: 276,
    google_maps_url: "https://maps.google.com/?cid=5",
    business_status: "OPERATIONAL",
    category: "bakery",
    priority_tier: 4,
    owner_name: "Faisal Malik",
    email: "faisal@heritagebakehouse.pk",
    instagram: "https://www.instagram.com/heritagebakehouse/",
    facebook: "https://www.facebook.com/heritagebakehouse/",
    linkedin: "Not found",
    additional_notes: "Well-established, may need a lower-priority follow-up cadence.",
  },
  {
    place_id: "mock-6",
    name: "Crumb & Co.",
    address: "17 DHA Phase 5, Lahore, Pakistan",
    phone: "+92 300 5551234",
    website: "https://crumbandco.pk/",
    has_website: true,
    rating: 4.1,
    review_count: 41,
    google_maps_url: "https://maps.google.com/?cid=6",
    business_status: "OPERATIONAL",
    category: "bakery",
    priority_tier: 2,
    owner_name: "Not found",
    email: "Not found",
    instagram: "https://www.instagram.com/crumbandco.pk/",
    facebook: "Not found",
    linkedin: "Not found",
    additional_notes: "Has website but no public email — good candidate for contact form outreach.",
  },
];
